[package]
name = "cs225-impl"
version = "0.1.0"
authors = ["Dan Cline <dan@dancline.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alga = "0.9.3"
rand = "0.7"
num = "0.3.0"
